// <auto-generated />
using HotelListing.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelListing.API.Migrations
{
    [DbContext(typeof(HotelListingDBContext))]
    partial class HotelListingDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HotelListing.API.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Indonesia",
                            ShortName = "ID"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Singapore",
                            ShortName = "SG"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Malaysia",
                            ShortName = "MY"
                        });
                });

            modelBuilder.Entity("HotelListing.API.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Batam, Hotel 1",
                            CountryId = 1,
                            Name = "Hotel 1",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "Batam, Hotel 2",
                            CountryId = 1,
                            Name = "Hotel 2",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 3,
                            Address = "Batam, Hotel 3",
                            CountryId = 2,
                            Name = "Hotel 3",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 4,
                            Address = "Batam, Hotel 4",
                            CountryId = 2,
                            Name = "Hotel 4",
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = 5,
                            Address = "Batam, Hotel 5",
                            CountryId = 3,
                            Name = "Hotel 5",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 6,
                            Address = "Batam, Hotel 6",
                            CountryId = 3,
                            Name = "Hotel 6",
                            Rating = 4.2000000000000002
                        });
                });

            modelBuilder.Entity("HotelListing.API.Data.Hotel", b =>
                {
                    b.HasOne("HotelListing.API.Data.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HotelListing.API.Data.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
